### PR TITLE
Log api blind except

### PR DESCRIPTION
**Pull request by maresb**
Log the otherwise blind except. (`LOGGER.exception` is supposed to print a stack trace.)

TO BE TESTED

checklist:

- [ ] tested the changes live by using the `dev` version of the action

### CODE REVIEW

**Comment by maresb** [comment]
Checks failing until #15 is merged

**Comment by beckermr** [comment]
You need to merge main into your branch.

**Comment by maresb** [comment]
Thanks! Shall I rebase the other PRs, or will that mess you up?

**Comment by beckermr** [comment]
Wait a bit and I'll let you know.

**Pull request merged**
