### PR TITLE
Rework dockerfile

### PR DESCRIPTION
**Pull request by maresb**
- Break out requirements into a separate `environment.yml` (useful for local installation)
- Bump Python to 3.11
- Generate Conda environment in a separate stage (saves ~11% space without conda/micromamba)
  - required switching shell to `sh` since `bash` isn't in the latest alpine image (I had to replace real activation by adding `/opt/conda/bin` to `PATH`)

checklist:

- [ ] tested the changes live by using the `dev` version of the action

### CODE REVIEW

**Comment by maresb** [comment]
Checks failing until #15 is merged

**Comment by maresb** [comment]
I implemented a lockfile in #16. Would it make sense to close this in favor of that?

**Comment by beckermr** [comment]
I am not a huge fan of lock files, and since I've been the primary developer here, I have not been using them. Mostly, I don't want to have to go around remembering to redo the lock files. 

If this bit of maintenance is something you want to take on, then feel free to switch to them. Otherwise, I think we should stick with what is here now.

**Comment by maresb** [comment]
Ok, maybe we should find a more reliable URL then.

**Comment by beckermr** [comment]
Let's use this one: https://loripsum.net/api

xref: https://github.com/conda-forge/docker-images/blob/main/linux-anvil-cos7-x86_64/Dockerfile#L22

**Comment by beckermr** [comment]
I'll go ahead and test the other two PRs first, and then do this one since it is the most complex.

**Comment by maresb** [comment]
Sounds great, thanks! In case you need passing checks in the other PRs, I can open a separate PR to switch the URL also in `main`.

**Comment by beckermr** [comment]
Sorry for the conflict. Rebase on master and resolve it, then we can test this one.

**Pull request merged**
